# Generated by Django 3.1.6 on 2021-03-01 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='post_image',
        ),
    ]
