# Generated by Django 3.1.6 on 2021-03-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blogpost_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='post_image',
            field=models.ImageField(default='default', upload_to='post_image'),
        ),
    ]
